replay_blacklist_regex:
  formadist.cnfpt.fr:
    - https://formadist.cnfpt.fr/Files/Applications
  any: []
  example.com:
    - http://example.com/complexRequest###i
    - https?://example.com/some(.*?)
  cnfptembed.libcast.com: "*"
  embed.api.video: "*"