replay_blacklist_regex:
  formadist.cnfpt.fr:
    - http://example.com/complexRequest###i
  any: []
  player.vimeo.com: "*"
  example.com:
    - http://example.com/complexRequest###i
    - https?://example.com/some(.*?)
  cnfptembed.libcast.com: "*"
  embed.api.video: "*"